name: Tag and Release on PR Merge

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  tag-merged-commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the merged commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract version from app.json
        id: get_version
        run: |
          VERSION=$(jq -r '.expo.version' app.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: tag_check
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping."
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Git tag on merge commit
        if: steps.tag_check.outputs.tag_exists == 'false'
        run: |
          git tag "v${{ steps.get_version.outputs.version }}" ${{ github.event.pull_request.merge_commit_sha }}
          git push origin "v${{ steps.get_version.outputs.version }}"

      - name: Create GitHub Release
        if: steps.tag_check.outputs.tag_exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
